package com.example

import com.example.ui.AppLanguage

object Translator {
    private val translations = mapOf(
        AppLanguage.EN to mapOf(
            "tab_posts" to "Posts",
            "tab_stories" to "Stories",
            "tab_highlights" to "Highlights",
            "tab_library" to "Library",
            "toast_session" to "Logged in as %s",
            "toast_logged_out" to "Logged out successfully",
            "app_title" to "IG Vault Downloader",
            "session_active" to "Session Active: %s",
            "session_guest" to "Guest Mode (Private profile restriction)",
            "sign_in" to "Sign In",
            "search_placeholder" to "Search Instagram username...",
            "badge_private" to "Private",
            "badge_public" to "Public",
            "posts_lbl" to "Posts",
            "followers_lbl" to "Followers",
            "following_lbl" to "Following",
            "welcome_title" to "IG Vault Download Hub",
            "welcome_subtitle" to "Enter any target Instagram username above to search and download posts, reels, carousel images, or active slide stories instantly.",
            "no_posts" to "No posts loaded. Searched profile posts will display here.",
            "access_blocked" to "Access Blocked",
            "login_details" to "Instagram blocks anonymous client connections to stories. Please login to your personal Instagram account via our secure viewer, enabling story scanning.",
            "login_prompt" to "Login to Instagram",
            "no_stories" to "No active stories found for this profile in the last 24h.",
            "login_details_highlights" to "Instagram requires login to view highlights. Please login to your personal Instagram account via our secure viewer, enabling highlights scanning.",
            "highlights_tray" to "Highlights Tray",
            "no_highlights" to "No highlights found for this profile.",
            "select_highlight_folder" to "Select a highlight folder above to load pinned stories.",
            "no_items_highlight" to "No items found in this highlight folder.",
            "total_assets" to "Total Assets: %d items",
            "btn_select_all" to "Select All",
            "btn_clear" to "Clear",
            "storage_empty" to "Offline Storage Empty.",
            "selected_lbl" to "%d selected",
            "downloading" to "Downloading...",
            "download_all" to "Download Selected",
            "expand_btn" to "Show Profile",
            "tab_tracking" to "Saved",
            "btn_follow" to "Bookmark",
            "btn_unfollow" to "Bookmarked",
            "msg_monitoring_info" to "Logged-in sessions regularly scan for target updates on start, triggering status bar alerts on new posts! (Simulated scanning is active in guest mode)",
            "no_notifications" to "No update alerts logged yet.",
            "no_follows" to "You are not following any tracked profile yet.",
            "btn_refresh_scans" to "Scan Updates",
            "scanning_status" to "Scanning..."
        ),
        AppLanguage.JA to mapOf(
            "tab_posts" to "投稿",
            "tab_stories" to "ストーリー",
            "tab_highlights" to "ハイライト",
            "tab_library" to "ライブラリ",
            "toast_session" to "%sとしてログイン中",
            "toast_logged_out" to "ログアウトしました",
            "app_title" to "IG Vault保存機",
            "session_active" to "セッション有効: %s",
            "session_guest" to "ゲストモード（非公開制限あり）",
            "sign_in" to "サインイン",
            "search_placeholder" to "ユーザー名を入力...",
            "badge_private" to "非公開",
            "badge_public" to "公開",
            "posts_lbl" to "投稿",
            "followers_lbl" to "フォロワー",
            "following_lbl" to "フォロー中",
            "welcome_title" to "IG Vaultダウンロードハブ",
            "welcome_subtitle" to "ユーザー名を入力して、投稿、リール、またはストーリーを検索して即座に保存できます。",
            "no_posts" to "投稿はありません。検索された投稿がここに表示されます。",
            "access_blocked" to "アクセス制限",
            "login_details" to "ストーリーを表示するにはログインが必要です。プライバシーへのセキュリティ保護のため安全な個人アカウントログインを使用してください。",
            "login_prompt" to "Instagramにログイン",
            "no_stories" to "直近24時間に有効なアクティブストーリーはありません。",
            "login_details_highlights" to "ハイライトをスキャンするにはログインが必要です。安全なビューア経由でログインしてください。",
            "highlights_tray" to "ハイライトトレイ",
            "no_highlights" to "このプロファイルのハイライトは見つかりませんでした。",
            "select_highlight_folder" to "ハイライトフォルダを選択してピン留めされたストーリーをロードします。",
            "no_items_highlight" to "ハイライトフォルダ内にアイテムが見つかりません。",
            "total_assets" to "合計アセット: %d 件",
            "btn_select_all" to "すべて選択",
            "btn_clear" to "クリア",
            "storage_empty" to "オフラインストレージは空です。",
            "selected_lbl" to "%d 件選択",
            "downloading" to "ダウンロード中...",
            "download_all" to "選択分を保存",
            "expand_btn" to "プロファイル表示",
            "tab_tracking" to "フォロー",
            "btn_follow" to "自動検知・フォロー",
            "btn_unfollow" to "フォロー中",
            "msg_monitoring_info" to "ログインセッションは開始時に自動的に更新を検出し、新しい投稿がある場合はシステム通知を送信します（ゲストモードでもシミュレートされます）。",
            "no_notifications" to "更新通知はまだありません。",
            "no_follows" to "フォローしているユーザーがいません。",
            "btn_refresh_scans" to "更新を確認",
            "scanning_status" to "スキャン中..."
        ),
        AppLanguage.ZH to mapOf(
            "tab_posts" to "帖子",
            "tab_stories" to "故事快照",
            "tab_highlights" to "精选合辑",
            "tab_library" to "离线库",
            "toast_session" to "已成功登录为 %s",
            "toast_logged_out" to "已安全注销登出",
            "app_title" to "IG Vault极客下载",
            "session_active" to "在线会话: %s",
            "session_guest" to "访客模式 (限制获取私有账号)",
            "sign_in" to "安全登录",
            "search_placeholder" to "请输入Instagram用户名...",
            "badge_private" to "私密",
            "badge_public" to "公开",
            "posts_lbl" to "帖子",
            "followers_lbl" to "粉丝",
            "following_lbl" to "关注",
            "welcome_title" to "IG Vault 极速下载枢纽",
            "welcome_subtitle" to "在此输入目标Instagram用户名，即可一键搜索并离线保存图片、视频、轮播和高亮快照。",
            "no_posts" to "暂无帖子数据。搜寻到的帖子媒体将展现在此。",
            "access_blocked" to "访问受限",
            "login_details" to "Instagram限制匿名故事快照获取。请通过我们安全的内置浏览器登录以开展故事扫描。",
            "login_prompt" to "登录 Instagram",
            "no_stories" to "该用户在过去24小时内未发布任何公开故事。",
            "login_details_highlights" to "Instagram需要登录才能查看精选文件夹。请安全登录以解锁全量精选归档拉取。",
            "highlights_tray" to "精选分类",
            "no_highlights" to "此账号未发现任何精选故事合辑。",
            "select_highlight_folder" to "点击上方的精选合辑图标即可展开和拉取该合辑下的媒体详情。",
            "no_items_highlight" to "此精选文件夹下暂不存在任何可见底片数据。",
            "total_assets" to "可下载媒体源: %d 项",
            "btn_select_all" to "全选",
            "btn_clear" to "清除",
            "storage_empty" to "离线下载历史库当前为空。",
            "selected_lbl" to "已选中 %d 项",
            "downloading" to "正在极速多线程保存...",
            "download_all" to "本地保存选中",
            "expand_btn" to "展开资料",
            "tab_tracking" to "监视关注",
            "btn_follow" to "开启更新监视",
            "btn_unfollow" to "持续监视中",
            "msg_monitoring_info" to "登录会话将在打开应用时自动扫频，遇新帖即刻弹窗通知栏提醒（访客模式自带模拟检测演示）",
            "no_notifications" to "暂无新消息记录。",
            "no_follows" to "您当前还未开启任何账号的更新追踪监督。",
            "btn_refresh_scans" to "扫频检索",
            "scanning_status" to "正在扫频..."
        ),
        AppLanguage.VI to mapOf(
            "tab_posts" to "Bài viết",
            "tab_stories" to "Tin",
            "tab_highlights" to "Nổi bật",
            "tab_library" to "Thư viện",
            "toast_session" to "Đã đăng nhập dưới tên %s",
            "toast_logged_out" to "Đã đăng xuất thành công",
            "app_title" to "Trình tải IG Vault",
            "session_active" to "Phiên hoạt động: %s",
            "session_guest" to "Chế độ khách (Không thể tải profile riêng tư)",
            "sign_in" to "Đăng nhập",
            "search_placeholder" to "Tìm tên người dùng Instagram...",
            "badge_private" to "Riêng tư",
            "badge_public" to "Công khai",
            "posts_lbl" to "Bài viết",
            "followers_lbl" to "Người theo dõi",
            "following_lbl" to "Đang theo dõi",
            "welcome_title" to "IG Vault Download Hub",
            "welcome_subtitle" to "Nhập tên người dùng Instagram bất kỳ phía trên để tìm kiếm và tải xuống bài viết, thước phim, ảnh quay vòng hoặc tin nổi bật lập tức.",
            "no_posts" to "Không có bài viết nào được tải. Bài viết tìm kiếm sẽ xuất hiện ở đây.",
            "access_blocked" to "Trình tải bị chặn",
            "login_details" to "Instagram chặn kết nối ẩn danh tới tin. Vui lòng đăng nhập tài khoản Instagram cá nhân của bạn qua trình xem an toàn để quét tin.",
            "login_prompt" to "Đăng nhập Instagram",
            "no_stories" to "Không có tin hoạt động nào từ tài khoản này trong 24 giờ qua.",
            "login_details_highlights" to "Instagram yêu cầu đăng nhập để hiển thị tin nổi bật. Vui lòng đăng nhập tài khoản qua trình xem an toàn để tiếp tục.",
            "highlights_tray" to "Thư mục Nổi bật",
            "no_highlights" to "Không tìm thấy thư mục nổi bật nào cho tài khoản này.",
            "select_highlight_folder" to "Chọn một thư mục nổi bật phía trên để hiển thị danh sách tin đã ghim.",
            "no_items_highlight" to "Không có tin nào thuộc thư mục nổi bật này.",
            "total_assets" to "Tổng tài nguyên: %d mục",
            "btn_select_all" to "Chọn tất cả",
            "btn_clear" to "Bỏ chọn",
            "storage_empty" to "Lịch sử tải xuống trống.",
            "selected_lbl" to "Đã chọn %d mục",
            "downloading" to "Đang tải xuống...",
            "download_all" to "Tải xuống các mục đã chọn",
            "expand_btn" to "Hiện profile",
            "tab_tracking" to "Đã lưu",
            "btn_follow" to "Đánh dấu",
            "btn_unfollow" to "Đã đánh dấu",
            "msg_monitoring_info" to "Phiên đăng nhập sẽ tự động quét thông tin khi mở ứng dụng và gửi thông báo điện thoại nếu có bài viết mới! (Có giả lập ở chế độ khách)",
            "no_notifications" to "Chưa có thông báo cập nhật nào được ghi nhận.",
            "no_follows" to "Bạn chưa nhấn theo dõi tài khoản nào để nhận thông báo tự động.",
            "btn_refresh_scans" to "Quét cập nhật",
            "scanning_status" to "Đang quét..."
        ),
        AppLanguage.AR to mapOf(
            "tab_posts" to "منشورات",
            "tab_stories" to "قصص",
            "tab_highlights" to "أبرز القصص",
            "tab_library" to "المكتبة",
            "toast_session" to "تم تسجيل الدخول باسم %s",
            "toast_logged_out" to "تم تسجيل الخروج بنجاح",
            "app_title" to "منزل IG Vault",
            "session_active" to "الجلسة نشطة: %s",
            "session_guest" to "وضع الضيف (قيود الحساب الخاص)",
            "sign_in" to "تسجيل الدخول",
            "search_placeholder" to "ابحث عن اسم المستخدم في إنستغرام...",
            "badge_private" to "حساب خاص",
            "badge_public" to "حساب عام",
            "posts_lbl" to "منشورات",
            "followers_lbl" to "متابعون",
            "following_lbl" to "متابع",
            "welcome_title" to "مركز تحميل IG Vault",
            "welcome_subtitle" to "أدخل أي اسم مستخدم على إنستغرام أعلاه للبحث وتنزيل المنشورات ومقاطع الريلز وصور الكاروسيل والقصص النشطة فوراً.",
            "no_posts" to "لم يتم تحميل أي منشورات. ستظهر منشورات الملف الشخصي المبحوث عنها هنا.",
            "access_blocked" to "تم حظر الوصول",
            "login_details" to "يحظر إنستغرام اتصالات العملاء المجهولين بالقصص. يرجى تسجيل الدخول لتفعيل ميزة المسح.",
            "login_prompt" to "تسجيل الدخول في إنستغرام",
            "no_stories" to "لم يتم العثور على قصص نشطة لهذا الملف الشخصي خلال الـ 24 ساعة الماضية.",
            "login_details_highlights" to "يتطلب إنستغرام تسجيل الدخول لعرض أبرز القصص. يرجى تسجيل الدخول عبر متصفحنا الآمن لتمكين مسح أبرز القصص.",
            "highlights_tray" to "شريط أبرز القصص",
            "no_highlights" to "لم يتم العثور على قصص بارزة لهذا الملف الشخصي.",
            "select_highlight_folder" to "اختر مجلد أبرز القصص أعلاه لتحميل القصص المثبتة.",
            "no_items_highlight" to "لم يتم العثور على عناصر في مجلد أبرز القصص هذا.",
            "total_assets" to "إجمالي العناصر: %d",
            "btn_select_all" to "تحديد الكل",
            "btn_clear" to "إلغاء التحديد",
            "storage_empty" to "مخزن التنزيلات فارغ.",
            "selected_lbl" to "تم تحديد %d",
            "downloading" to "جاري التحميل...",
            "download_all" to "تنزيل المحدد",
            "expand_btn" to "عرض الملف",
            "tab_tracking" to "المتابعة",
            "btn_follow" to "تتبع التحديثات",
            "btn_unfollow" to "قيد التتبع",
            "msg_monitoring_info" to "سوف تقوم جلسات تسجيل الدخول بالمسح التلقائي على التحديثات وتنبيهك عند نشر منشورات جديدة (المسح المحاكي نشط للضيوف)",
            "no_notifications" to "لا توجد تنبيهات جديدة بعد.",
            "no_follows" to "أنت لا تتابع أي ملفات شخصية للتحديثات بعد.",
            "btn_refresh_scans" to "فحص التحديثات",
            "scanning_status" to "جاري الفحص..."
        )
    )

    fun get(key: String, lang: AppLanguage): String {
        return translations[lang]?.get(key) ?: translations[AppLanguage.EN]?.get(key) ?: key
    }
}
